
[[gi-install-opennms-debian]]
== Debian/Ubuntu

IMPORTANT: This guide does not apply to OpenNMS Meridian, which can be installed only on Red Hat Enterprise Linux or CentOS systems.

Create a new apt source file (eg: `/etc/apt/sources.list.d/opennms.list`), and add the following 2 lines:

.Package repository configuration for Debian-based systems
[source, shell]
----
deb https://debian.opennms.org ${RELEASE} main <1>
deb-src https://debian.opennms.org ${RELEASE} main <1>
----

<1> Replace `${RELEASE}` with a release name like `stable` (recommended), `testing`, or `snapshot`.

Import the packages' authentication key with the following command:

.GPG key import for Debian-based systems
[source, shell]
----
wget -O - https://debian.opennms.org/OPENNMS-GPG-KEY | apt-key add -
----

[[gi-install-oracle-java-debian]]
=== Install Oracle JDK

This section describes how to install _Oracle Java SE Development Kit 8_ on a _Debian-based_ system like _Debian 8_ or _Ubuntu 14.04 LTS_.

.Add Java repository from webupd8 maintainer
[source, bash]
----
su -
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
----

.Add repository key server and update repository
[source, bash]
----
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update
----

.Install Oracle Java SE Development Kit 8
[source, bash]
----
apt-get install -y oracle-java8-installer
----

To locate the _Java_ system files, applications typically use the `$JAVA_HOME` environment variable.
The environment can be set for a specific user or globally for the whole system on boot time.

.Example path to Java on RHEL, Debian and Microsoft Windows systems
* RHEL: `/usr/java/jdk1.8.0_51`
* Debian: `/usr/lib/jvm/java-8-oracle`
* Microsoft Windows: `C:\Program Files\Java\jre1.8.0_51`

.Option 1: Set the Java environment for the current user
[source, bash]
----
vi ~/.bash_profile
export JAVA_HOME=/path/to/java
----

.Option 2: Set the Java environment for all users on boot time
[source, bash]
----
vi /etc/profile
export JAVA_HOME=/path/to/java
----

=== Installing the R package (Optional)

link:https://www.r-project.org/[R] is a free software environment for statistical computing and graphics.
_{product-title}_ can leverage the power of _R_ for forecasting and advanced calculations on collected time series data.

_{product-title}_ interfaces with _R_ via _stdin_ and _stdout_, and for this reason, _R_ must be installed on the same host as _{product-title}_.
Note that installing _R_ is optional, and not required by any of the core components.

This section describes how to install _R_ on a _Debian_-based system.

NOTE: This description was built on _Debian 8_ and _Ubuntu 14.04 LTS_.

.Install R
[source, bash]
----
sudo apt-get install r-recommended
----

[[gi-install-opennms-deb-package]]
=== Install OpenNMS

.Installation of the full application with all dependencies like PostgreSQL and Java
[source, shell]
----
apt-get update
apt-get install -y opennms
----

The following packages will be automatically installed:

* _opennms_: The platform meta package which handles all dependencies from _OpenNMS_ repository.
* _jicmp6_ and _jicmp_: _Java_ bridge to allow sending _ICMP messages_ from _OpenNMS_ repository.
* _opennms-core_: _OpenNMS_ core services, e.g. _Provisiond_, _Pollerd_ and _Collectd_ from _OpenNMS_ repository.
* _opennms-webapp-jetty_: _OpenNMS_ web application from _OpenNMS_ repository
* _postgresql_: _PostgreSQL_ database server from distribution repository
* _postgresql-libs_: _PostgreSQL_ database from distribution repository

TIP: Verify the version of the _OpenNMS_ packages that was installed with `apt-cache show opennms`.

With the successful installed packages the _OpenNMS_ platform is installed in the following directory structure:

[source, shell]
----
[root@localhost /usr/share/opennms]# tree -L 2
.
└── opennms
   ├── bin
   ├── data
   ├── deploy
   ├── etc -> /etc/opennms
   ├── instances
   ├── jetty-webapps
   ├── lib -> ../java/opennms
   ├── logs -> /var/log/opennms
   ├── share -> /var/lib/opennms
   └── system
----

[[gi-install-opennms-deb-disable-update]]
=== Disable Automatic Updates (Optional)

We recommend you disable automatic updating of the {opennms-product-name} packages to avoid upgrades while it is running.

{opennms-product-name} requires some manual steps upon upgrade to make sure the database and configuration are consistent in the new version, and on systems with many nodes or lots of events, this can take hours.
For this reason, it is recommended to exclude the {opennms-product-name} packages from update except when you are planning on performing an upgrade.

To do so, run:

[source, shell]
----
sudo apt-mark hold libopennms-java \
     libopennmsdeps-java \
     opennms-common opennms-db
----

When you are ready to upgrade {opennms-product-name}, unhold them and upgrade, then hold them again:

[source, shell]
----
sudo apt-mark unhold libopennms-java \
     libopennmsdeps-java \
     opennms-common opennms-db

sudo apt-get upgrade opennms

sudo apt-mark hold libopennms-java \
     libopennmsdeps-java \
     opennms-common opennms-db
----

[[gi-install-opennms-deb-prepare-pg]]
=== Prepare PostgreSQL

The _Debian_ package installs also _PostgreSQL_ database and is already initialized and added in the runlevel configuration.
It is only necessary to start the _PostgreSQL_ database without a restart.

.Startup PostgreSQL database
[source, shell]
----
service postgresql start
----

The next step is creating an _opennms_ database user with password and configure the authentication method.

.Accounting and database management for _OpenNMS_
[source, shell]
----
su - postgres
createuser -P opennms
createdb -O opennms opennms
exit
----

NOTE: It is not necessary to change the authentication method in `pg_hba.conf`, it is by default set to `md5` for localhost connections.

.Set password for Postgres super user
[source, shell]
----
su - postgres
psql -c "ALTER USER postgres WITH PASSWORD 'YOUR-POSTGRES-PASSWORD';"
exit
----

NOTE: The super user is required to be able to initialize and change the database schema for installation and updates.

[source, shell]
----
vi ${OPENNMS_HOME}/etc/opennms-datasources.xml
----

.Configuration for database authentication in _OpenNMS_
[source, xml]
----
<jdbc-data-source name="opennms"
                    database-name="opennms"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/opennms"
                    user-name="** YOUR-OPENNMS-USERNAME **"<1>
                    password="** YOUR-OPENNMS-PASSWORD **" /><2>

<jdbc-data-source name="opennms-admin"
                    database-name="template1"
                    class-name="org.postgresql.Driver"
                    url="jdbc:postgresql://localhost:5432/template1"
                    user-name="postgres"<3>
                    password="** YOUR-POSTGRES-PASSWORD **" /><4>
----

<1> Set the user name to access the _OpenNMS_ database table
<2> Set the password to access the _OpenNMS_ database table
<3> Set the _postgres_ user for administrative access to PostgreSQL
<4> Set the password for administrative access to PostgreSQL

[[gi-install-opennms-deb-init]]
=== Initialize OpenNMS

_OpenNMS_ is now configured to access the database.
It is required to set the _Java_ environment running _OpenNMS_ and initialize the database schema.

.Configuration of _Java_ environment for _OpenNMS_
[source, shell]
----
${OPENNMS_HOME}/bin/runjava -s
----

.Initialization of database and system libraries
[source, shell]
----
${OPENNMS_HOME}/bin/install -dis
----

NOTE: It is not necessary to add _OpenNMS_ to the run level manually, it is automatically added after setup.

.Startup _OpenNMS_
[source, shell]
----
service opennms start
----

After starting OpenNMS, the web application can be accessed on http://<ip-or-fqdn-of-your-server>:8980/opennms.
The default login user is _admin_ and the password is initialized to _admin_.

IMPORTANT: Change the default admin password to a secure password immediately.
